### ISSUE TITLE
Uncaught TypeError: Cannot set property 'listener' of undefined

### ISSUE THREAD

**Issue by davidvhill** [JunoLab/atom-ink#108]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.7
**Electron Version**: 1.3.13
**System**: Ubuntu 16.04.1
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package, v0.6.2

### Stack Trace

Uncaught TypeError: Cannot set property 'listener' of undefined

```
At /home/david/.atom/packages/ink/lib/console/console.js:385

TypeError: Cannot set property 'listener' of undefined
    at /home/david/.atom/packages/ink/lib/console/console.js:385:42
```

### Commands

```
     -0:29.2.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
     -0:29.2.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:28 core:move-up (atom-text-editor.editor.is-focused)
     -0:27.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:27 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
     -0:27 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:21.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:19.7.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:17 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:14.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.6.0 proto-repl:execute-text-entered-in-repl (atom-text-editor.editor.is-focused)
     -0:13.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:00.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.1.0 core:move-up (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited"
  }
}
```

### Installed Packages

```coffee
# User
ink, v0.6.2 (active)
lisp-paredit, v0.5.4 (active)
Parinfer, v1.16.0 (active)
proto-repl, v1.4.10 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by mkborregaard** [comment]
I get this all the time

**Comment by MikeInnes** [comment]
This should be fixed on master / next release

**Comment by crbinz** [comment]
This still happens to me with v0.6.5 of ink:

[Enter steps to reproduce:]

1. `using Plots`
2. [arrow up/down a few times]

**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5


### Stack Trace

Uncaught TypeError: Cannot set property 'listener' of undefined

```
At /Users/cbinz/.atom/packages/ink/lib/console/console.js:385

TypeError: Cannot set property 'listener' of undefined
    at /packages/ink/lib/console/console.js:385:42
```

### Commands

```
     -6:00.5.0 console:evaluate (input.hidden-input)
     -6:00.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -5:49.4.0 julia-client:kill-julia (input.hidden-input)
     -5:36.8.0 console:evaluate (input.hidden-input)
     -5:36.8.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -4:36 julia-client:kill-julia (input.hidden-input)
     -4:32.3.0 console:evaluate (input.hidden-input)
     -4:32.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -3:55.9.0 console:evaluate (input.hidden-input)
     -3:55.9.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -3:29.8.0 julia-client:kill-julia (input.hidden-input)
     -3:25.5.0 console:evaluate (input.hidden-input)
  2x -3:25.5.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  5x -2:28.9.0 core:move-up (input.hidden-input)
     -1:00.6.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
     -0:19.1.0 settings-view:open (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
ink 0.6.5 
Jude 0.2.9 
julia-client 0.5.12 
language-julia 0.10.0 
latex 0.42.3 
linter 1.11.23 
vim-mode 0.66.0 
```

**Comment by timlod** [comment]
1. using Plots
2. core:move-up (or down)

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Ubuntu 16.04.2
**Thrown From**: [ink](https://github.com/JunoLab/atom-ink) package 0.6.5


### Stack Trace

Uncaught TypeError: Cannot set property 'listener' of undefined

```
At /home/tim/.atom/packages/ink/lib/console/console.js:385

TypeError: Cannot set property 'listener' of undefined
    at /packages/ink/lib/console/console.js:385:42
```

### Commands

```
     -4:21.1.0 core:backspace (input.hidden-input)
     -4:20.3.0 console:evaluate (input.hidden-input)
     -4:20.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
  8x -4:19.5.0 core:backspace (input.hidden-input)
     -4:16.3.0 console:evaluate (input.hidden-input)
     -4:16.3.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
  4x -4:14.7.0 core:move-up (input.hidden-input)
     -4:13.6.0 core:move-down (input.hidden-input)
     -4:09.6.0 core:move-up (input.hidden-input)
  3x -4:06.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
 10x -0:47.4.0 core:backspace (input.hidden-input)
     -0:38.6.0 core:move-up (input.hidden-input)
 13x -0:35.3.0 core:backspace (input.hidden-input)
 49x -0:33.9.0 core:move-up (input.hidden-input)
 48x -0:22.6.0 core:move-down (input.hidden-input)
     -0:09.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
disable-keybindings 0.6.0 
emacs-plus 0.11.1 
ink 0.6.5 
julia-client 0.5.12 
language-julia 0.11.0 
latex-completions 0.3.2 
tool-bar 1.1.0 
uber-juno 0.1.1 
```
