### ISSUE TITLE
ANSI colors missing from console

### ISSUE THREAD

**Issue by mauricioszabo** [JunoLab/atom-ink#175]
The new version of Ink broke ANSI escape codes from Ink console, like the screenshot below:

![image](https://user-images.githubusercontent.com/138037/45488859-1483c900-b739-11e8-9982-632bd33fe1bc.png)

As we're working with Clojure, running code inside editor, and sometimes diffs are shown on console, this is a big deal for me right now. I've checked that there's now two "console" folders on `lib`, and "console" still has the code for ANSI codes, but not on `console2`.

I'm using INK 0.9.6, on Atom 1.30.0, on Ubuntu 16.04

**Comment by pfitzseb** [comment]
Fixed with https://github.com/JunoLab/atom-ink/commit/18a708394698c6a23b9204d401d627599b969d16.

Could proto-repl switch to the new console implementation (in the `console2` dir), which is based on xterm.js? This one probably won't be maintained for much longer.

**Comment by pfitzseb** [comment]
New version is out, so this should work again. Please reopen if not.

**Comment by royvandewater** [comment]
I'm still seeing the issue after updating to 0.9.7

**Comment by pfitzseb** [comment]
Actually fixed in https://github.com/JunoLab/atom-ink/commit/0d9621d55bcb044af9d8b242a8c747410a770806.

New release should be out soonish.

**Comment by royvandewater** [comment]
I'm sorry, it looks like version 0.9.8 is still showing the escaped ANSI color codes instead of colorizing the output.

**Comment by pfitzseb** [comment]
Sigh... I think I've finally found a good test case (because the old code does work in most cases, at least for how Juno uses it), so this should be fixed for good now. 
Can you check the latest commit (should be as easy as `apm dev ink` and then start `atom -d`)? If it works fine for you I'll tag another release immediately.

**Comment by royvandewater** [comment]
I'll try that right away

**Comment by royvandewater** [comment]
It worked! Thank you for your patience with this, that had to be pretty frustrating!

**Comment by pfitzseb** [comment]
Ok, new version should be out :) Thanks for testing!

And yeah, me being so obtuse was kinda frustrating... :P
